# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BellObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BellGallery',
            fields=[
                ('bellobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gallery.BellObject')),
                ('name', models.CharField(max_length=35)),
                ('url', models.CharField(max_length=10)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
            ],
            bases=('gallery.bellobject',),
        ),
        migrations.CreateModel(
            name='BellImage',
            fields=[
                ('bellobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gallery.BellObject')),
                ('name', models.CharField(max_length=300)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('image_location', models.CharField(max_length=300)),
                ('thumbnail_location', models.CharField(max_length=300)),
                ('source_id', models.CharField(max_length=35, unique=True)),
                ('parent_gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.BellGallery')),
            ],
            bases=('gallery.bellobject',),
        ),
    ]
