# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-24 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bellimage',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
